sudo: required
dist: trusty
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
    - postfix
language: php
php:
  - 5.5
  - 5.6
  - 7.0
env:
  - TEST_SUITE=unit
  - TEST_SUITE=integration INTEGRATION_INDEX=1 INTEGRATION_SETS=2
  - TEST_SUITE=integration INTEGRATION_INDEX=2 INTEGRATION_SETS=2
  - TEST_SUITE=static_phpcs
  - TEST_SUITE=static_annotation
cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/bin
matrix:
  exclude:
    - php: 5.6
      env: TEST_SUITE=static_phpcs
    - php: 5.6
      env: TEST_SUITE=static_annotation
    - php: 7.0
      env: TEST_SUITE=static_phpcs
    - php: 7.0
      env: TEST_SUITE=static_annotation
before_install: ./dev/travis/before_install.sh
before_script: ./dev/travis/before_script.sh
script: ./dev/travis/script.sh
