apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: magento
    tier: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-server
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-server
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.default.svc.cluster.local
    path: "/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-pvc-1
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-2
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.default.svc.cluster.local
    path: "/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-pvc-2
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: magento
spec:
  replicas: 2
  selector:
    matchLabels:
      app: magento
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: magento
        tier: frontend
    spec:
      securityContext:
        fsGroup: 82
      initContainers:
        - name: copy-data
          image: eu.gcr.io/magento2-269418/magento2-php72:$TAG_NAME
          command: ["/bin/sh", "-c", "/tmp/start.sh"]
          volumeMounts:
          - mountPath: /var/www/html
            name: magento-shared
          resources:
            requests:
              cpu: "250m"
      containers:
        - image: eu.gcr.io/magento2-269418/magento2-apache24:$TAG_NAME
          name: apache
          ports:
            - containerPort: 80
              name: apache
          resources:
            requests:
              cpu: "250m"
            #limits:
            #  memory: "128Mi"
            #  cpu: "500m"
          volumeMounts:
          - mountPath: /var/www/html
            name: magento-shared
        - image: eu.gcr.io/magento2-269418/magento2-php72:$TAG_NAME
          name: php
          resources:
            requests:
              cpu: "250m"
            #limits:
            #  memory: "128Mi"
            #  cpu: "500m"
          ports:
            - containerPort: 9000
              name: php
          volumeMounts:
          - mountPath: /var/www/html
            name: magento-shared
          - mountPath: /var/www/html/magento/media
            name: magento-media-volume
            subPath: media
          - mountPath: /var/www/html/magento/var
            name: magento-var-volume
            subPath: var 
        - name: nfs-server
          env:
          - name: SHARED_DIRECTORY
            value: /data
          image: eu.gcr.io/magento2-269418/nfs-server-alpine:1
          ports:
            - name: nfs
              containerPort: 2049
            - name: mountd
              containerPort: 20048
            - name: rpcbind
              containerPort: 111        
          volumeMounts:
            - mountPath: /data
              name: nfs-pvc   
      nodeSelector: 
        private-app-pool: web-app
      volumes:
      - name: magento-shared
        emptyDir: {}
      - name: magento-media-volume
        persistentVolumeClaim:
          claimName: nfs-pvc-1
      - name: magento-var-volume
        persistentVolumeClaim:
          claimName: nfs-pvc-2
      - name: nfs-pvc
          gcePersistentDisk:
            pdName: nfs-disk
            fsType: ext4