apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: magento
    tier: frontend
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: magento-pv-claim
  labels:
    app: magento
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: magento
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magento
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: magento
        tier: frontend
    spec:
      securityContext:
        fsGroup: 82
      initContainers:
        - name: prep-php-symlink
          image: eu.gcr.io/magento2-269418/magento2-php72:$TAG_NAME
          command: ["bin/sh", "-ec", "ln -s /tmp /mnt/app/html"]
          volumeMounts:
          - mountPath: /mnt/app
            name: magento-shared
        - name: prep-apache-symlink
          image: eu.gcr.io/magento2-269418/magento2-apache24:$TAG_NAME
          command: ["bin/sh", "-ec", "ln -s /tmp /mnt/app/html"]
          volumeMounts:
          - mountPath: /mnt/app
            name: magento-shared
      containers:
        - image: eu.gcr.io/magento2-269418/magento2-apache24:$TAG_NAME
          name: apache
          ports:
            - containerPort: 80
              name: apache
          volumeMounts:
          - mountPath: /mnt/app
            name: magento-shared
            subPath: html
        - image: eu.gcr.io/magento2-269418/magento2-php72:$TAG_NAME
          name: php
          ports:
            - containerPort: 9000
              name: php
          volumeMounts:
          - mountPath: /mnt/app
            name: magento-shared
            subPath: html
          - mountPath: /var/www/magento/media
            name: magento-persistent-storage
            subPath: media
          - mountPath: /var/www/magento/var
            name: magento-persistent-storage
            subPath: var 
      volumes:
      - name: magento-shared
        emptyDir: {}
      - name: magento-persistent-storage
        persistentVolumeClaim:
          claimName: magento-pv-claim