apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: magento
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: magento
spec:
  replicas: 2
  selector:
    matchLabels:
      app: magento
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: magento
        tier: frontend
    spec:
      securityContext:
        supplementalGroups:
          - 82
        fsGroup: 82
      initContainers:
        - name: setup-pub-dir
          image: eu.gcr.io/magento2-269418/magento2-php72:$TAG_NAME
          securityContext:
            runAsUser: 0
          volumeMounts:
          - mountPath: /var/www/html/pub
            name: magento-pub-volume
            subPath: pub
          command: ["/bin/sh","-c","/var/www/html/start.sh"]
          command: 
            - sh
            - -c
            - (chmod 0775 /var/www/html/pub; chgrp 82 /var/www/html/pub)
          resources:
            requests:
              cpu: "250m"
      containers:
        - image: eu.gcr.io/magento2-269418/magento2-apache24:$TAG_NAME
          name: apache
          ports:
            - containerPort: 80
              name: apache
          resources:
            requests:
              cpu: "250m"
            #limits:
            #  memory: "128Mi"
            #  cpu: "500m"
          volumeMounts:
          - mountPath: /var/www/html/pub
            name: magento-pub-volume
            subPath: pub
        - image: eu.gcr.io/magento2-269418/magento2-php72:$TAG_NAME
          name: php
          resources:
            requests:
              cpu: "250m"
            #limits:
            #  memory: "128Mi"
            #  cpu: "500m"
          ports:
            - containerPort: 9000
              name: php
          volumeMounts:
          - mountPath: /var/www/html/pub
            name: magento-pub-volume
            subPath: pub
          - mountPath: /var/www/html/var
            name: magento-var-volume
            subPath: var   
      nodeSelector: 
        private-app-pool: web-app
      volumes:
      - name: magento-pub-volume
        persistentVolumeClaim:
          claimName: nfs-pvc-1
      - name: magento-var-volume
        persistentVolumeClaim:
          claimName: nfs-pvc-2