apiVersion: v1
items:
- apiVersion: autoscaling/v2beta2
  kind: HorizontalPodAutoscaler
  metadata:
    creationTimestamp: "2020-06-22T14:06:17Z"
    name: magento
    namespace: default
    resourceVersion: "65703"
    selfLink: /apis/autoscaling/v2beta2/namespaces/default/horizontalpodautoscalers/magento
    uid: 097917ad-3d45-4308-85eb-6ffba1fa2b51
  spec:
    maxReplicas: 5
    metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 50
          type: Utilization
      type: Resource
    minReplicas: 1
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: magento
  status:
    conditions:
    - lastTransitionTime: "2020-06-22T14:06:39Z"
      message: recommended size matches current size
      reason: ReadyForNewScale
      status: "True"
      type: AbleToScale
    - lastTransitionTime: "2020-06-22T14:06:39Z"
      message: the HPA was able to successfully calculate a replica count from cpu
        resource utilization (percentage of request)
      reason: ValidMetricFound
      status: "True"
      type: ScalingActive
    - lastTransitionTime: "2020-06-22T14:47:27Z"
      message: the desired replica count is increasing faster than the maximum scale
        rate
      reason: TooFewReplicas
      status: "True"
      type: ScalingLimited
    currentMetrics:
    - resource:
        current:
          averageUtilization: 0
          averageValue: 1m
        name: cpu
      type: Resource
    currentReplicas: 1
    desiredReplicas: 1
    lastScaleTime: "2020-06-22T14:19:43Z"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
