apiVersion: batch/v1
kind: Job
metadata:
  name: post-release-actions
spec:
  template:
    spec:
      containers:
      - name: php
        image: eu.gcr.io/magento2-269418/magento2-php72:$TAG_NAME
        command: ["/bin/sh", "-c", "/var/www/html/start.sh"]
      restartPolicy: Never
  backoffLimit: 4
