apiVersion: batch/v1
kind: Job
metadata:
  name: pre-release-actions
spec:
  template:
    spec:
      securityContext:
        supplementalGroups:
          - 82
        fsGroup: 82
      containers:
      - name: php
        image: eu.gcr.io/magento2-269418/magento2-php72:$TAG_NAME
        volumeMounts:
          - mountPath: /var/www/html/var
            name: magento-var-volume
            subPath: var
        securityContext:
          runAsUser: 0
        command: ["/bin/sh", "-c", "chmod -R 0775 /var/www/html/var; chgrp -R 82 /var/www/html/var; /var/www/html/start.sh; chgrp -R 82 /var/www/html/var"]
      volumes:
      - name: magento-var-volume
        persistentVolumeClaim:
          claimName: nfs-pvc-2
      restartPolicy: Never
  backoffLimit: 4
